### ISSUE TITLE
/Punishlookup Virker ikke

### ISSUE THREAD

**Issue by StickingPinning** [Uraxys/SkyLands-Info#28]
Punishlookup virker ikke i survival.
Det er også noe vi trenger.

**Comment by Uraxys** [comment]
... Punishlookup is not even a survival command....
It is a bungee command, please test before reporting.

If you want to report a bug, please give more information then just "Uhhh, command no work on x server."

Be more like, 
Punishlookup is not working on survival,
I tried to do this command: INSERT COMMAND HERE
What happen when I did that command was I got a error in red, it told me "BLa bla bla".

(Some extra information)
I don't want you to type the command you did, you should copy & paste it from the game,
as you might have not used the right format of the command, this will also make sure I can check the command you did!

Example:
*Cp types in game /plookup**s** Cp1987*
**It won't work**
*Cp reports it on github and says he typed /plookup*

As we can see, I typed it wrong in game but not on github, this wastes my time as I am checking for a bug that could have been solved by reading a copy & past of a command you did ingame.

Example on the things above:

*Mod1 types in game /plookup**s** Cp1987*
**It won't work**
*Mod1 reports it on github and says he typed /plookup*
*Cp looks at it for some hours but can't find anything...*

This could have been solved by doing this:
*Mod1 types in game /plookup**s** Cp1987*
**It won't work**
*Mod1 reports it on github and copies the command he did in game with CTRL A the CTRL C*
*It now says on github: I used this command: /plookup**s** bla bla.*
**Cp can now see that you typed it wrong.**

Your problem is invalid, please type the correct name next time.

`2018-03-20 16:39:58
Player Noahgb01 used command '/Punishlookup zNigthWishOG_YT'!
Rank : MODERATOR
Server : Survival`

You typed 'zNigthWishOG_YT', while his name is 'zNightWishOG_YT'.
